vim.cmd("colorscheme onedark")
vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = "none" })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { bg = "none", fg = "#cccccc" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { bg = "none", fg = "#cccccc" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextOk", { bg = "none", fg = "#cccccc" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { bg = "none", fg = "#00cccc" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { bg = "none", fg = "#cc0000" })
