add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""
